const {chromium,webkit}=require('playwright');
const fs=require('fs');const path=require('path');const root=path.resolve(__dirname,'..');fs.mkdirSync(path.join(root,'test-results'),{recursive:true});const base=process.env.BASE_URL||'http://127.0.0.1:8138';
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH});const report=[];const themes=['classic','journal','holo','pocket','studio'];
for(const [i,theme] of themes.entries()){
const context=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1});const page=await context.newPage();let errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`${base}/0${i+1}-${theme}.html`);await page.waitForTimeout(150);
await page.screenshot({path:path.join(root,`test-results/${theme}-home.png`)});
for(const width of [320,390,480]){await page.setViewportSize({width,height:844});const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);if(overflow)throw Error(`${theme} overflow ${width}`)}
await page.setViewportSize({width:390,height:844});await page.locator('nav [data-go="capture"]').click();await page.locator('[data-demo]').click();await page.locator('[data-save]').waitFor();await page.locator('[data-save]').click();await page.locator('nav [data-go="collection"]').click();if(await page.locator('.collection-card').count()!==1)throw Error('Card not saved');await page.reload();await page.locator('nav [data-go="collection"]').click();if(await page.locator('.collection-card').count()!==1)throw Error('Card not persisted');await page.locator('[data-open]').click();await page.locator('[data-save]').click();await page.locator('nav [data-go="collection"]').click();if(await page.locator('.collection-card').count()!==1)throw Error('Duplicate card');
await page.locator('nav [data-go="kana"]').click();await page.locator('.kana-key').first().waitFor();const hira=await page.locator('.kana-key').count();if(hira!==46)throw Error('Missing hiragana');await page.locator('[data-script="katakana"]').click();await page.locator('.kana-key').first().waitFor();const kata=await page.locator('.kana-key').count();if(kata!==46)throw Error('Missing katakana');await page.locator('.kana-key').first().click();if(!await page.locator('#kana-now').innerText().then(t=>t.includes('ア')))throw Error('Kana selection');await page.screenshot({path:path.join(root,`test-results/${theme}-kana.png`)});
await page.locator('nav [data-go="collection"]').click();await page.locator('[data-go="review"]').click();await page.locator('[data-reveal]').click();await page.locator('[data-review-next]').click();if(await page.locator('[data-reveal]').count()!==1)throw Error('Recall reset');
await page.locator('nav [data-go="capture"]').click();await page.locator('[data-demo]').click();await page.locator('[data-cancel]').click();await page.waitForTimeout(1600);if(await page.locator('[data-demo]').count()!==1)throw Error('Cancelled demo replaced current screen');
if(errors.length)throw Error(errors.join(';'));report.push({theme,viewports:[320,390,480],hiragana:hira,katakana:kata,save:'passed',deduplication:'passed',reload:'passed',recall:'passed',cancel:'passed',errors});await context.close();}
await browser.close();fs.writeFileSync(path.join(root,'test-results/ui-report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));})().catch(e=>{console.error(e);process.exit(1)});
