const {chromium}=require('playwright');
const fs=require('fs');const path=require('path');
const root=path.resolve(__dirname,'..');
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH});
 const ctx=await browser.newContext({viewport:{width:390,height:844},recordVideo:{dir:path.join(root,'test-results/video'),size:{width:390,height:844}}});
 const page=await ctx.newPage();
 await page.goto((process.env.DEMO_URL||'http://127.0.0.1:8142')+'/demo/01-classic.html');
 await page.evaluate(()=>Promise.all([...document.images].map(i=>i.decode())));
 await page.waitForTimeout(1700);
 await page.locator('[data-sample="chair"]').first().click();
 await page.waitForTimeout(2000);
 await page.locator('#finish').selectOption('foil');
 await page.locator('.cardface').scrollIntoViewIfNeeded();
 await page.waitForTimeout(1800);
 await page.locator('[data-save]').click();
 await page.waitForTimeout(800);
 await page.locator('nav [data-go="collection"]').click();
 await page.waitForTimeout(1700);
 await page.locator('nav [data-go="kana"]').click();
 await page.locator('.kana-key').first().waitFor();
 await page.waitForTimeout(1800);
 await page.locator('[data-script="katakana"]').click();
 await page.waitForTimeout(1700);
 await page.locator('nav [data-go="home"]').click();
 await page.waitForTimeout(1500);
 const video=page.video();await ctx.close();
 await video.saveAs(path.join(root,'test-results/walkthrough.webm'));
 await browser.close();console.log('Recorded real sample app walkthrough.');
})().catch(error=>{console.error(error);process.exit(1)});
